server:
  port: ${PORT:8080}
  error:
    include-message: always
    include-binding-errors: always

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:tidb}
  application:
    name: smartprocure-backend
  jpa:
    open-in-view: false
  mail:
    host: ${SPRING_MAIL_HOST:smtp.gmail.com}
    port: ${SPRING_MAIL_PORT:587}
    username: ${SPRING_MAIL_USERNAME:no-reply@smartprocure.com}
    password: ${SPRING_MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
